extern const GeoLayout sht_area_1_geo[];
extern const GeoLayout sht_area_1[];
extern const Collision sht_area_1_collision[];
extern const MacroObject sht_area_1_macro_objs[];
extern Lights1 sht_dl_sm64_material_001_lights;
extern Vtx sht_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx sht_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_sht_dl_sm64_material_001[];
extern Gfx sht_dl_Cube_mesh_layer_1[];
extern Gfx sht_dl_material_revert_render_settings[];
