extern const GeoLayout gf_area_1_geo[];
extern const GeoLayout gf_area_1[];
extern const Collision gf_area_1_collision[];
extern const MacroObject gf_area_1_macro_objs[];
extern Lights1 gf_dl_f3dlite_material_lights;
extern Vtx gf_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx gf_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_gf_dl_f3dlite_material[];
extern Gfx gf_dl_Cube_mesh_layer_1[];
extern Gfx gf_dl_material_revert_render_settings[];
