extern const GeoLayout bbf2_area_1_geo[];
extern const GeoLayout bbf2_area_1[];
extern const Collision bbf2_area_1_collision[];
extern const MacroObject bbf2_area_1_macro_objs[];
extern Lights1 bbf2_dl_f3dlite_material_lights;
extern Vtx bbf2_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bbf2_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_bbf2_dl_f3dlite_material[];
extern Gfx bbf2_dl_Cube_mesh_layer_1[];
extern Gfx bbf2_dl_material_revert_render_settings[];
