extern const GeoLayout ct_area_1_geo[];
extern const GeoLayout ct_area_1[];
extern const Collision ct_area_1_collision[];
extern const MacroObject ct_area_1_macro_objs[];
extern Lights1 ct_dl_f3dlite_material_lights;
extern Vtx ct_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ct_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ct_dl_f3dlite_material[];
extern Gfx ct_dl_Cube_mesh_layer_1[];
extern Gfx ct_dl_material_revert_render_settings[];
