extern const GeoLayout hhh_area_1_geo[];
extern const GeoLayout hhh_area_1[];
extern const Collision hhh_area_1_collision[];
extern const MacroObject hhh_area_1_macro_objs[];
extern Lights1 hhh_dl_f3dlite_material_lights;
extern Vtx hhh_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx hhh_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_hhh_dl_f3dlite_material[];
extern Gfx hhh_dl_Cube_mesh_layer_1[];
extern Gfx hhh_dl_material_revert_render_shhhtings[];
