extern const GeoLayout tc_area_1_geo[];
extern const GeoLayout tc_area_1[];
extern const Collision tc_area_1_collision[];
extern const MacroObject tc_area_1_macro_objs[];
extern Lights1 tc_dl_f3dlite_material_lights;
extern Vtx tc_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx tc_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_tc_dl_f3dlite_material[];
extern Gfx tc_dl_Cube_mesh_layer_1[];
extern Gfx tc_dl_material_revert_render_settings[];
