extern const GeoLayout tc_area_1_geo[];
extern const GeoLayout tc_area_1[];
extern const Collision tc_area_1_collision[];
extern const MacroObject tc_area_1_macro_objs[];
extern Lights1 tc_dl_f3dlite_material_001_layer1_area1_lights;
extern Lights1 tc_dl_f3dlite_material_layer4_area1_lights;
extern Lights1 tc_dl_f3dlite_material_002_layer1_area1_lights;
extern Lights1 tc_dl_f3dlite_material_005_layer1_area1_lights;
extern u8 tc_dl_gb6_rgba16[];
extern u8 tc_dl_ttm_textures_08000_rgba16_ci8[];
extern u8 tc_dl_ttm_textures_08000_rgba16_pal_rgba16[];
extern u8 tc_dl_hmc_textures_09800_rgba16_ci8[];
extern u8 tc_dl_hmc_textures_09800_rgba16_pal_rgba16[];
extern u8 tc_dl_acfgh_rgba16[];
extern u8 tc_dl_hmc_textures_06800_rgba16_ci8[];
extern u8 tc_dl_hmc_textures_06800_rgba16_pal_rgba16[];
extern Vtx tc_dl_Cube_mesh_layer_1_vtx_0[247];
extern Gfx tc_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx tc_dl_Cube_mesh_layer_1_vtx_1[86];
extern Gfx tc_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx tc_dl_Cube_mesh_layer_1_vtx_2[16];
extern Gfx tc_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx tc_dl_Cube_mesh_layer_1_vtx_3[42];
extern Gfx tc_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx tc_dl_Cube_mesh_layer_4_vtx_0[39];
extern Gfx tc_dl_Cube_mesh_layer_4_tri_0[];
extern Gfx mat_tc_dl_f3dlite_material_001_layer1_area1[];
extern Gfx mat_revert_tc_dl_f3dlite_material_001_layer1_area1[];
extern Gfx mat_tc_dl_f3dlite_material_layer4_area1[];
extern Gfx mat_revert_tc_dl_f3dlite_material_layer4_area1[];
extern Gfx mat_tc_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_revert_tc_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_tc_dl_sm64_water_mat[];
extern Gfx mat_tc_dl_f3dlite_material_005_layer1_area1[];
extern Gfx mat_revert_tc_dl_f3dlite_material_005_layer1_area1[];
extern Gfx tc_dl_Cube_mesh_layer_1[];
extern Gfx tc_dl_Cube_mesh_layer_4[];
extern Gfx tc_dl_material_revert_render_settings[];
