extern const GeoLayout delicious_cake_area_1_geo[];
extern const GeoLayout delicious_cake_area_1[];
extern const Collision delicious_cake_area_1_collision[];
extern const MacroObject delicious_cake_area_1_macro_objs[];
extern Lights1 delicious_cake_dl_f3dlite_material_lights;
extern Vtx delicious_cake_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx delicious_cake_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_delicious_cake_dl_f3dlite_material[];
extern Gfx delicious_cake_dl_Cube_mesh_layer_1[];
extern Gfx delicious_cake_dl_material_revert_render_settings[];
