extern const GeoLayout mmm_area_1_geo[];
extern const GeoLayout mmm_area_1[];
extern const Collision mmm_area_1_collision[];
extern const MacroObject mmm_area_1_macro_objs[];
extern Lights1 mmm_dl_f3dlite_material_lights;
extern Vtx mmm_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx mmm_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_mmm_dl_f3dlite_material[];
extern Gfx mmm_dl_Cube_mesh_layer_1[];
extern Gfx mmm_dl_material_revert_render_settings[];
