extern const GeoLayout cw_area_1_geo[];
extern const GeoLayout cw_area_1[];
extern const Collision cw_area_1_collision[];
extern const MacroObject cw_area_1_macro_objs[];
extern Lights1 cw_dl_f3dlite_material_lights;
extern Vtx cw_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx cw_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_cw_dl_f3dlite_material[];
extern Gfx cw_dl_Cube_mesh_layer_1[];
extern Gfx cw_dl_material_revert_render_settings[];
