extern const GeoLayout dbd_area_1_geo[];
extern const GeoLayout dbd_area_1[];
extern const Collision dbd_area_1_collision[];
extern const MacroObject dbd_area_1_macro_objs[];
extern Lights1 dbd_dl_f3dlite_material_lights;
extern Vtx dbd_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx dbd_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_dbd_dl_f3dlite_material[];
extern Gfx dbd_dl_Cube_mesh_layer_1[];
extern Gfx dbd_dl_material_revert_render_settings[];
