extern const GeoLayout ppf_area_1_geo[];
extern const GeoLayout ppf_area_1[];
extern const Collision ppf_area_1_collision[];
extern const MacroObject ppf_area_1_macro_objs[];
extern const GeoLayout ppf_area_2_geo[];
extern const GeoLayout ppf_area_2[];
extern const Collision ppf_area_2_collision[];
extern const MacroObject ppf_area_2_macro_objs[];
extern Lights1 ppf_dl_f3dlite_material_015_lights;
extern Lights1 ppf_dl_f3dlite_material_016_lights;
extern Lights1 ppf_dl_f3dlite_material_017_lights;
extern Lights1 ppf_dl_f3dlite_material_018_lights;
extern Lights1 ppf_dl_f3dlite_material_001_lights;
extern Lights1 ppf_dl_f3dlite_material_003_lights;
extern Lights1 ppf_dl_f3dlite_material_002_lights;
extern Lights1 ppf_dl_f3dlite_material_023_lights;
extern Lights1 ppf_dl_f3dlite_material_024_lights;
extern u8 ppf_dl_ppf_dl_ppf_dl_ccm_textures_03000_rgba16_ci8_ci8_001_ci8[];
extern u8 ppf_dl_ppf_dl_ppf_dl_ccm_textures_03000_rgba16_ci8_ci8_001_pal_rgba16[];
extern u8 ppf_dl_ppf_dl_ppf_dl_bob_textures_05800_rgba16_ci8_ci8_001_ci8[];
extern u8 ppf_dl_ppf_dl_ppf_dl_bob_textures_05800_rgba16_ci8_ci8_001_pal_rgba16[];
extern u8 ppf_dl_ppf_dl_ppf_dl_bob_textures_02000_rgba16_ci8_ci8_001_ci8[];
extern u8 ppf_dl_ppf_dl_ppf_dl_bob_textures_02000_rgba16_ci8_ci8_001_pal_rgba16[];
extern u8 ppf_dl_ppf_dl_ppf_dl__2_rgba16_rgba16_rgba16_001_rgba16[];
extern u8 ppf_dl_segment2_11C58_rgba16_rgba16[];
extern u8 ppf_dl_ccm_textures_03000_rgba16_rgba16[];
extern Vtx ppf_dl_ppf_mesh_layer_1_vtx_0[909];
extern Gfx ppf_dl_ppf_mesh_layer_1_tri_0[];
extern Vtx ppf_dl_ppf_mesh_layer_1_vtx_1[201];
extern Gfx ppf_dl_ppf_mesh_layer_1_tri_1[];
extern Vtx ppf_dl_ppf_mesh_layer_1_vtx_2[42];
extern Gfx ppf_dl_ppf_mesh_layer_1_tri_2[];
extern Vtx ppf_dl_ppf_mesh_layer_1_vtx_3[45];
extern Gfx ppf_dl_ppf_mesh_layer_1_tri_3[];
extern Vtx ppf_dl_ppf_mesh_layer_5_vtx_0[12];
extern Gfx ppf_dl_ppf_mesh_layer_5_tri_0[];
extern Vtx ppf_dl_ppf_mesh_layer_5_vtx_1[4];
extern Gfx ppf_dl_ppf_mesh_layer_5_tri_1[];
extern Vtx ppf_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx ppf_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx ppf_dl_cave_mesh_layer_1_vtx_0[103];
extern Gfx ppf_dl_cave_mesh_layer_1_tri_0[];
extern Vtx ppf_dl_cave_mesh_layer_1_vtx_1[24];
extern Gfx ppf_dl_cave_mesh_layer_1_tri_1[];
extern Gfx mat_ppf_dl_f3dlite_material_015[];
extern Gfx mat_revert_ppf_dl_f3dlite_material_015[];
extern Gfx mat_ppf_dl_f3dlite_material_016[];
extern Gfx mat_revert_ppf_dl_f3dlite_material_016[];
extern Gfx mat_ppf_dl_f3dlite_material_017[];
extern Gfx mat_revert_ppf_dl_f3dlite_material_017[];
extern Gfx mat_ppf_dl_f3dlite_material_018[];
extern Gfx mat_ppf_dl_f3dlite_material_001[];
extern Gfx mat_revert_ppf_dl_f3dlite_material_001[];
extern Gfx mat_ppf_dl_f3dlite_material_003[];
extern Gfx mat_revert_ppf_dl_f3dlite_material_003[];
extern Gfx mat_ppf_dl_f3dlite_material_002[];
extern Gfx mat_revert_ppf_dl_f3dlite_material_002[];
extern Gfx mat_ppf_dl_f3dlite_material_023[];
extern Gfx mat_ppf_dl_f3dlite_material_024[];
extern Gfx ppf_dl_ppf_mesh_layer_1[];
extern Gfx ppf_dl_ppf_mesh_layer_5[];
extern Gfx ppf_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx ppf_dl_cave_mesh_layer_1[];
extern Gfx ppf_dl_material_revert_render_settings[];
