extern const GeoLayout tsss_area_1_geo[];
extern const GeoLayout tsss_area_1[];
extern const Collision tsss_area_1_collision[];
extern const MacroObject tsss_area_1_macro_objs[];
extern Lights1 tsss_dl_f3dlite_material_lights;
extern Vtx tsss_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx tsss_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_tsss_dl_f3dlite_material[];
extern Gfx tsss_dl_Cube_mesh_layer_1[];
extern Gfx tsss_dl_material_revert_render_settings[];
