extern const GeoLayout tsns_area_1_geo[];
extern const GeoLayout tsns_area_1[];
extern const Collision tsns_area_1_collision[];
extern const MacroObject tsns_area_1_macro_objs[];
extern Lights1 tsns_dl_sm64_material_001_lights;
extern Vtx tsns_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx tsns_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_tsns_dl_sm64_material_001[];
extern Gfx tsns_dl_Cube_mesh_layer_1[];
extern Gfx tsns_dl_material_revert_render_settings[];
