extern const GeoLayout bowser_4_area_1_geo[];
extern const GeoLayout bowser_4_area_1[];
extern const Collision bowser_4_area_1_collision[];
extern const MacroObject bowser_4_area_1_macro_objs[];
extern Lights1 bowser_4_dl_f3dlite_material_lights;
extern Vtx bowser_4_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bowser_4_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_bowser_4_dl_f3dlite_material[];
extern Gfx bowser_4_dl_Cube_mesh_layer_1[];
extern Gfx bowser_4_dl_material_revert_render_settings[];
