extern const GeoLayout sss_area_1_geo[];
extern const GeoLayout sss_area_1[];
extern const Collision sss_area_1_collision[];
extern const MacroObject sss_area_1_macro_objs[];
extern Lights1 sss_dl_f3dlite_material_lights;
extern Vtx sss_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx sss_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_sss_dl_f3dlite_material[];
extern Gfx sss_dl_Cube_mesh_layer_1[];
extern Gfx sss_dl_material_revert_render_settings[];
