extern const GeoLayout pop_area_1_geo[];
extern const GeoLayout pop_area_1[];
extern const Collision pop_area_1_collision[];
extern const MacroObject pop_area_1_macro_objs[];
extern Lights1 pop_dl_f3dlite_material_lights;
extern Vtx pop_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx pop_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_pop_dl_f3dlite_material[];
extern Gfx pop_dl_Cube_mesh_layer_1[];
extern Gfx pop_dl_material_revert_render_settings[];
