extern const GeoLayout faf_area_1_geo[];
extern const GeoLayout faf_area_1[];
extern const Collision faf_area_1_collision[];
extern const MacroObject faf_area_1_macro_objs[];
extern Lights1 faf_dl_f3dlite_material_lights;
extern Vtx faf_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx faf_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_faf_dl_f3dlite_material[];
extern Gfx faf_dl_Cube_mesh_layer_1[];
extern Gfx faf_dl_material_revert_render_settings[];
