#include "src/game/envfx_snow.h"

const GeoLayout small_chain_chomp_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 200),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -257, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, small_chain_chomp_000_offset_001_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, small_chain_chomp_001_offset_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -257, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, small_chain_chomp_000_offset_002_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, small_chain_chomp_001_offset_001_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, small_chain_chomp_002_offset_001_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, small_chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, small_chain_chomp_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
