extern const GeoLayout ff_area_1_geo[];
extern const GeoLayout ff_area_1[];
extern const Collision ff_area_1_collision[];
extern const MacroObject ff_area_1_macro_objs[];
extern Lights1 ff_dl_sm64_material_001_lights;
extern Vtx ff_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ff_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ff_dl_sm64_material_001[];
extern Gfx ff_dl_Cube_mesh_layer_1[];
extern Gfx ff_dl_material_revert_render_settings[];
