extern const GeoLayout ss_area_1_geo[];
extern const GeoLayout ss_area_1[];
extern const Collision ss_area_1_collision[];
extern const MacroObject ss_area_1_macro_objs[];
extern Lights1 ss_dl_f3dlite_material_lights;
extern Vtx ss_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ss_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ss_dl_f3dlite_material[];
extern Gfx ss_dl_Cube_mesh_layer_1[];
extern Gfx ss_dl_material_revert_render_settings[];
