extern const GeoLayout statue_geo[];
extern u8 statue_castle_grounds_textures_00800_rgba16_rgba16[];
extern u8 statue_castle_grounds_textures_08800_rgba16_i8[];
extern u8 statue_castle_grounds_textures_04800_rgba16_i8[];
extern Vtx statue_Bone_mesh_layer_1_vtx_0[20];
extern Gfx statue_Bone_mesh_layer_1_tri_0[];
extern Vtx statue_Bone_mesh_layer_1_vtx_1[4];
extern Gfx statue_Bone_mesh_layer_1_tri_1[];
extern Vtx statue_Bone_mesh_layer_1_vtx_2[51];
extern Gfx statue_Bone_mesh_layer_1_tri_2[];
extern Gfx mat_statue_f3dlite_material_004[];
extern Gfx mat_revert_statue_f3dlite_material_004[];
extern Gfx mat_statue_f3dlite_material_008[];
extern Gfx mat_revert_statue_f3dlite_material_008[];
extern Gfx mat_statue_f3dlite_material_010[];
extern Gfx mat_revert_statue_f3dlite_material_010[];
extern Gfx statue_Bone_mesh_layer_1[];
extern Gfx statue_material_revert_render_settings[];
