extern const GeoLayout bov_area_1_geo[];
extern const GeoLayout bov_area_1[];
extern const Collision bov_area_1_collision[];
extern const MacroObject bov_area_1_macro_objs[];
extern Lights1 bov_dl_f3dlite_material_lights;
extern Vtx bov_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bov_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_bov_dl_f3dlite_material[];
extern Gfx bov_dl_Cube_mesh_layer_1[];
extern Gfx bov_dl_material_revert_render_settings[];
