extern const GeoLayout po_area_1_geo[];
extern const GeoLayout po_area_1[];
extern const Collision po_area_1_collision[];
extern const MacroObject po_area_1_macro_objs[];
extern Lights1 po_dl_f3dlite_material_lights;
extern Vtx po_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx po_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_po_dl_f3dlite_material[];
extern Gfx po_dl_Cube_mesh_layer_1[];
extern Gfx po_dl_material_revert_render_settings[];
