extern const GeoLayout ll_area_1_geo[];
extern const GeoLayout ll_area_1[];
extern const Collision ll_area_1_collision[];
extern const MacroObject ll_area_1_macro_objs[];
extern Lights1 ll_dl_f3dlite_material_lights;
extern Vtx ll_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ll_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ll_dl_f3dlite_material[];
extern Gfx ll_dl_Cube_mesh_layer_1[];
extern Gfx ll_dl_material_revert_render_settings[];
