extern const GeoLayout yi_area_1_geo[];
extern const GeoLayout yi_area_1[];
extern const Collision yi_area_1_collision[];
extern const MacroObject yi_area_1_macro_objs[];
extern Lights1 yi_dl_f3dlite_material_lights;
extern Vtx yi_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx yi_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_yi_dl_f3dlite_material[];
extern Gfx yi_dl_Cube_mesh_layer_1[];
extern Gfx yi_dl_material_revert_render_settings[];
