extern const GeoLayout www_area_1_geo[];
extern const GeoLayout www_area_1[];
extern const Collision www_area_1_collision[];
extern const MacroObject www_area_1_macro_objs[];
extern Lights1 www_dl_f3dlite_material_lights;
extern Vtx www_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx www_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_www_dl_f3dlite_material[];
extern Gfx www_dl_Cube_mesh_layer_1[];
extern Gfx www_dl_material_revert_render_settings[];
