extern const GeoLayout ccb_area_1_geo[];
extern const GeoLayout ccb_area_1[];
extern const Collision ccb_area_1_collision[];
extern const MacroObject ccb_area_1_macro_objs[];
extern Lights1 ccb_dl_f3dlite_material_lights;
extern Vtx ccb_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ccb_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ccb_dl_f3dlite_material[];
extern Gfx ccb_dl_Cube_mesh_layer_1[];
extern Gfx ccb_dl_material_revert_render_settings[];
