extern const GeoLayout hh_area_1_geo[];
extern const GeoLayout hh_area_1[];
extern const Collision hh_area_1_collision[];
extern const MacroObject hh_area_1_macro_objs[];
extern Lights1 hh_dl_f3dlite_material_lights;
extern Vtx hh_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx hh_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_hh_dl_f3dlite_material[];
extern Gfx hh_dl_Cube_mesh_layer_1[];
extern Gfx hh_dl_material_revert_render_settings[];
