extern const GeoLayout et_area_1_geo[];
extern const GeoLayout et_area_1[];
extern const Collision et_area_1_collision[];
extern const MacroObject et_area_1_macro_objs[];
extern Lights1 et_dl_f3dlite_material_lights;
extern Vtx et_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx et_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_et_dl_f3dlite_material[];
extern Gfx et_dl_Cube_mesh_layer_1[];
extern Gfx et_dl_material_revert_render_settings[];
