extern const GeoLayout aa_area_1_geo[];
extern const GeoLayout aa_area_1[];
extern const Collision aa_area_1_collision[];
extern const MacroObject aa_area_1_macro_objs[];
extern Lights1 aa_dl_f3dlite_material_lights;
extern Vtx aa_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx aa_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_aa_dl_f3dlite_material[];
extern Gfx aa_dl_Cube_mesh_layer_1[];
extern Gfx aa_dl_material_revert_render_settings[];
