extern const GeoLayout kbs_area_1_geo[];
extern const GeoLayout kbs_area_1[];
extern const Collision kbs_area_1_collision[];
extern const MacroObject kbs_area_1_macro_objs[];
extern Lights1 kbs_dl_f3dlite_material_lights;
extern Vtx kbs_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx kbs_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_kbs_dl_f3dlite_material[];
extern Gfx kbs_dl_Cube_mesh_layer_1[];
extern Gfx kbs_dl_material_revert_render_settings[];
