extern const GeoLayout ktp_area_1_geo[];
extern const GeoLayout ktp_area_1[];
extern const Collision ktp_area_1_collision[];
extern const MacroObject ktp_area_1_macro_objs[];
extern Lights1 ktp_dl_sm64_material_001_lights;
extern Vtx ktp_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ktp_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ktp_dl_sm64_material_001[];
extern Gfx ktp_dl_Cube_mesh_layer_1[];
extern Gfx ktp_dl_material_revert_render_settings[];
