extern const GeoLayout ppv_area_1_geo[];
extern const GeoLayout ppv_area_1[];
extern const Collision ppv_area_1_collision[];
extern const MacroObject ppv_area_1_macro_objs[];
extern Lights1 ppv_dl_f3dlite_material_lights;
extern Vtx ppv_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ppv_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ppv_dl_f3dlite_material[];
extern Gfx ppv_dl_Cube_mesh_layer_1[];
extern Gfx ppv_dl_material_revert_render_settings[];
