extern const GeoLayout ef_area_1_geo[];
extern const GeoLayout ef_area_1[];
extern const Collision ef_area_1_collision[];
extern const MacroObject ef_area_1_macro_objs[];
extern Lights1 ef_dl_f3dlite_material_lights;
extern Vtx ef_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ef_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ef_dl_f3dlite_material[];
extern Gfx ef_dl_Cube_mesh_layer_1[];
extern Gfx ef_dl_material_revert_render_settings[];
