extern const GeoLayout ddd2_area_1_geo[];
extern const GeoLayout ddd2_area_1[];
extern const Collision ddd2_area_1_collision[];
extern const MacroObject ddd2_area_1_macro_objs[];
extern Lights1 ddd2_dl_f3dlite_material_lights;
extern Vtx ddd2_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ddd2_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ddd2_dl_f3dlite_material[];
extern Gfx ddd2_dl_Cube_mesh_layer_1[];
extern Gfx ddd2_dl_material_revert_render_settings[];
