extern const GeoLayout ac_area_1_geo[];
extern const GeoLayout ac_area_1[];
extern const Collision ac_area_1_collision[];
extern const MacroObject ac_area_1_macro_objs[];
extern Lights1 ac_dl_f3dlite_material_lights;
extern Vtx ac_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ac_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ac_dl_f3dlite_material[];
extern Gfx ac_dl_Cube_mesh_layer_1[];
extern Gfx ac_dl_material_revert_render_settings[];
